import path from 'path';
import isDev from 'electron-is-dev';

export type Args = {
  zip: string;
  mobilePassphrase?: string;
  mobileRsa?: string;
  rsaKey: string;
  rsaKeyPassphrase?: string;
  autoGeneratedPassphrase: boolean;
  dangerouslyRecoverPrivateKeys?: boolean;
};

export type ExecArgs = {
  type: string;
  rsaFile: string;
  cipherText: string;
  rsaPass: string;
};

const EXECUTABLE_NAME = 'recover';

const basePath = path.join(__dirname, '..', '..', '..');

export const getChildProcessInput = (args: ExecArgs) => {
  const processArgs = [args.type, args.rsaFile, args.cipherText, args.rsaPass];

  let file: string;

  if (isDev) {
    const executablePath = path.join(basePath, 'packages', 'py-dec', `${EXECUTABLE_NAME}.py`);

    file = 'python';

    processArgs.unshift(executablePath);
  } else {
    const executablePath = path.join(basePath, EXECUTABLE_NAME, process.platform === 'win32' ? '.exe' : '');

    file = executablePath;
  }

  return { file, processArgs };
};
