import { Page } from 'playwright-core';
import { AssetTestConfig } from './types';

const nativeTestnetAssets: AssetTestConfig[] = [
  // { assetId: 'ADA_TEST', postTestFn: async (utility: Page, relay: Page) => await relay.pause() },
  // { assetId: 'ALGO_TEST' },
  // { assetId: 'ATOM_COS_TEST' },
  // { assetId: 'AVAXTEST' },
  // { assetId: 'BCH_TEST' },
  // { assetId: 'BCHA_TEST' },
  // { assetId: 'BNB_TEST' },
  // { assetId: 'BSV_TEST' },
  // { assetId: 'BTC_TEST' },
  // { assetId: 'CELO_ALF' },
  // { assetId: 'CELO_BAK' },
  // { assetId: 'CELESTIA_TEST' },
  // { assetId: 'CORE_COREDAO_TEST' },
  // { assetId: 'DASH_TEST' },
  // { assetId: 'DIEM_XUS_TEST' },
  // { assetId: 'DOGE_TEST' },
  // { assetId: 'EOS_TEST' },
  // { assetId: 'ETC_TEST' },
  // { assetId: 'ETH_TEST' },
  // { assetId: 'ETH_TEST5' },
  // { assetId: 'ETH_TEST6', newEndpoint: 'https://1rpc.io/holesky' },
  // { assetId: 'ETH-AETH_RIN' },
  // { assetId: 'ETH-OPT_KOV' },
  // { assetId: 'HBAR_TEST' },
  // { assetId: 'LTC_TEST' },
  // { assetId: 'LUNA2_TEST' },
  // { assetId: 'NEAR_TEST' },
  // { assetId: 'RBTC_TEST' },
  // { assetId: 'SOL_TEST' },
  // { assetId: 'TRX_TEST' },
  // { assetId: 'VLX_TEST' },
  // { assetId: 'WND' },
  // { assetId: 'XDB_TEST' },
  // { assetId: 'XEC_TEST' },
  // { assetId: 'XEM_TEST' },
  // { assetId: 'XLM_TEST' },
  // { assetId: 'XRP_TEST' },
  // { assetId: 'XTZ_TEST' },
  // { assetId: 'ZEC_TEST' },
  // { assetId: 'TON_TEST' },
];

const nativeMainnetAssets = [
  // { assetId: 'ADA' },
  // { assetId: 'ALGO' },
  // { assetId: 'ATOM_COS' },
  // { assetId: 'AURORA_DEV' },
  // { assetId: 'AVAX' },
  // { assetId: 'BCH' },
  // { assetId: 'BCHA' },
  // { assetId: 'BNB_BSC' },
  // { assetId: 'BSV' },
  // { assetId: 'BTC' },
  // { assetId: 'CELO' },
  // { assetId: 'CHZ_$CHZ' },
  // { assetId: 'DASH' },
  // { assetId: 'DOGE' },
  // { assetId: 'DOT' },
  // { assetId: 'EOS' },
  // { assetId: 'ETC' },
  // { assetId: 'ETH' },
  // { assetId: 'ETH-AETH' },
  // { assetId: 'ETH-OPT' },
  // { assetId: 'ETHW' },
  // { assetId: 'EVMOS' },
  // { assetId: 'FTM_FANTOM' },
  // { assetId: 'GLMR_GLMR' },
  // { assetId: 'HBAR' },
  // { assetId: 'HT_CHAIN' },
  // { assetId: 'KSM' },
  // { assetId: 'LTC' },
  // { assetId: 'LUNA' },
  // { assetId: 'LUNA2' },
  // { assetId: 'MATIC_POLYGON' },
  // { assetId: 'MOVR_MOVR' },
  // { assetId: 'NEAR' },
  // { assetId: 'RBTC' },
  // { assetId: 'RON' },
  // { assetId: 'SGB' },
  // { assetId: 'SGB_LEGACY' },
  // { assetId: 'SMARTBCH' },
  // { assetId: 'SOL' },
  // { assetId: 'TERRA_KRW' },
  // { assetId: 'TERRA_MNT' },
  // { assetId: 'TERRA_SDR' },
  // { assetId: 'TERRA_USD' },
  // { assetId: 'TKX' },
  // { assetId: 'TRX' },
  // { assetId: 'VLX_VLX' },
  // { assetId: 'XDB' },
  // { assetId: 'XDC' },
  // { assetId: 'XEC' },
  // { assetId: 'XEM' },
  // { assetId: 'XLM' },
  // { assetId: 'XRP' },
  // { assetId: 'XTZ' },
  // { assetId: 'ZEC' },
  // { assetId: 'TON' },
];

export const testAssets: AssetTestConfig[] = [...nativeTestnetAssets, ...nativeMainnetAssets];
