import { z } from "zod";

export const decryptInput = z.object({
  pin: z
    .string()
    .trim()
    .length(6)
    .regex(/^[0-9]{6}$/g, "Must be a 6 digit number")
    .describe("Generated by Fireblocks Recovery Utility"),
});
