import path from 'path';
import fs from 'fs';
import prettier from 'prettier';

const GENERATED_HEADER = '// 🛑 DO NOT EDIT!!!\n// This file is automatically generated at build time.';

const distDir = path.join(__dirname, '..', 'dist');

export const writeObject = async (name: string, description: string, data: object) => {
  const dataStr = JSON.stringify(data, null, 2);

  const configStr = `${GENERATED_HEADER}\n\n/**\n * ${description}\n */\nexport const ${name} = ${dataStr};\n`;

  const formattedConfigStr = prettier.format(configStr, {
    parser: 'typescript',
  });

  const filePath = path.join(distDir, `${name}.ts`);

  await fs.promises.writeFile(filePath, formattedConfigStr);

  console.info(`Wrote ${name} to ${filePath}`);
};
