export const defaultRPCs: Record<
  string,
  {
    url: string | undefined | null;
    name: string;
    enabled: boolean;
    allowedEmptyValue: boolean;
    requiresApiKey?: boolean;
    apiKey?: string | null;
  }
> = {
  ALGO: { url: null, allowedEmptyValue: true, enabled: true, name: 'Algorand' },
  ALGO_TEST: { url: null, allowedEmptyValue: true, enabled: true, name: 'Algorand Testnet' },
  AVAX: { url: 'https://api.avax-test.network/ext/bc/C/rpc', name: 'Avalance C-Chain', enabled: true, allowedEmptyValue: false },
  AVAXTEST: {
    url: 'https://api.avax.network/ext/bc/C/rpc',
    name: 'Avalance C-Chain Testnet',
    enabled: true,
    allowedEmptyValue: false,
  },
  FLR: { url: 'https://flare-api.flare.network/ext/C/rpc', name: 'Flare', enabled: true, allowedEmptyValue: false },
  BTC: {
    url: 'https://api.blockchair.com/bitcoin',
    name: 'Bitcoin',
    enabled: true,
    allowedEmptyValue: false,
    requiresApiKey: true,
    apiKey: null,
  },
  BTC_TEST: {
    url: 'https://api.blockchair.com/bitcoin/testnet',
    name: 'Bitcoin Testnet',
    enabled: true,
    allowedEmptyValue: false,
    requiresApiKey: true,
    apiKey: null,
  },
  BCH: { url: 'https://rest.bch.actorforth.org/v2', name: 'Bitcoin Cash', enabled: true, allowedEmptyValue: false },
  BCH_TEST: { url: undefined, name: 'Bitcoin Cash Testnet', enabled: false, allowedEmptyValue: false },
  BSV: { url: 'https://api.whatsonchain.com/v1/bsv/main', name: 'Bitcoin-SV', enabled: true, allowedEmptyValue: false },
  BSV_TEST: {
    url: 'https://api.whatsonchain.com/v1/bsv/test',
    name: 'Bitcoin-SV Testnet',
    enabled: true,
    allowedEmptyValue: false,
  },
  DOGE: {
    url: 'https://api.blockchair.com/dogecoin',
    name: 'Dogecoin',
    enabled: true,
    allowedEmptyValue: false,
    requiresApiKey: true,
    apiKey: null,
  },
  DOGE_TEST: { url: undefined, name: 'Dogecoin Testnet', enabled: false, allowedEmptyValue: false },
  DOT: { url: 'wss://rpc.polkadot.io', name: 'Polkadot', enabled: true, allowedEmptyValue: false },
  WND: { url: 'wss://westend-rpc.polkadot.io', name: 'Westend (Polkadot Testnet)', enabled: true, allowedEmptyValue: false },
  KSM: { url: 'wss://kusama-rpc.polkadot.io', name: 'Kusama', enabled: true, allowedEmptyValue: false },
  LTC: {
    url: 'https://api.blockchair.com/litecoin',
    name: 'Litecoin',
    enabled: true,
    allowedEmptyValue: false,
    requiresApiKey: true,
    apiKey: null,
  },
  LTC_TEST: { url: undefined, name: 'Litecoin Testnet', enabled: false, allowedEmptyValue: false },
  ZEC: {
    url: 'https://api.blockchair.com/zcash',
    name: 'Litecoin',
    enabled: true,
    allowedEmptyValue: false,
    requiresApiKey: true,
    apiKey: null,
  },
  ZEC_TEST: { url: undefined, name: 'ZCash Testnet', enabled: false, allowedEmptyValue: false },
  DASH: {
    url: 'https://api.blockchair.com/Dash',
    name: 'Dash',
    enabled: true,
    allowedEmptyValue: false,
    requiresApiKey: true,
    apiKey: null,
  },
  FTM_FANTOM: { url: 'https://rpcapi.fantom.network', name: 'Fantom Testnet', enabled: true, allowedEmptyValue: false },
  ETC: { url: 'https://geth-de.etc-network.info', name: 'Ethereum Classic', enabled: true, allowedEmptyValue: false },
  ETC_TEST: {
    url: 'https://geth-mordor.etc-network.info',
    name: 'Ethereum Classic Testnet',
    enabled: true,
    allowedEmptyValue: false,
  },
  ETH: {
    url: 'https://eth-mainnet.public.blastapi.io',
    name: 'Ethereum',
    enabled: true,
    allowedEmptyValue: false,
  },
  ETH_TEST3: {
    url: 'https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161',
    name: 'Ethereum Goerli Testnet',
    enabled: true,
    allowedEmptyValue: false,
  },
  ETH_TEST5: {
    url: 'https://ethereum-sepolia-rpc.publicnode.com',
    name: 'Ethereum Sepolia Testnet',
    enabled: true,
    allowedEmptyValue: false,
  },
  ETH_TEST6: {
    url: 'https://ethereum-holesky-rpc.publicnode.com',
    name: 'Ethereum Holesky Testnet',
    enabled: true,
    allowedEmptyValue: false,
  },
  ETHW: { url: 'https://mainnet.ethereumpow.org', name: 'Ethereum PoW', enabled: true, allowedEmptyValue: false },
  EVMOS: { url: 'https://evmos-evm.publicnode.com', name: 'EVMOS', enabled: true, allowedEmptyValue: false },
  GLMR: { url: 'https://rpc.api.moonbeam.network', name: 'Moonbeam', enabled: true, allowedEmptyValue: false },
  CELO: { url: 'https://forno.celo.org', name: 'CELO', enabled: true, allowedEmptyValue: false },
  AURORA_DEV: { url: 'https://mainnet.aurora.dev', name: 'Aurora Dev', enabled: true, allowedEmptyValue: false },
  SOL: { url: 'https://api.mainnet-beta.solana.com', name: 'Solana', enabled: true, allowedEmptyValue: false },
  SOL_TEST: { url: 'https://api.devnet.solana.com', name: 'Solana Devnet', enabled: true, allowedEmptyValue: false },
  RON: { url: undefined, name: 'Ronin', enabled: true, allowedEmptyValue: true },
  XDC: { url: 'https://rpc.xinfin.network', name: 'XinFin', enabled: true, allowedEmptyValue: false },
  XRP: { url: 'wss://xrplcluster.com/', name: 'Ripple', enabled: true, allowedEmptyValue: false },
  XRP_TEST: { url: 'wss://s.altnet.rippletest.net:51233', name: 'Ripple Testnet', enabled: true, allowedEmptyValue: false },
  RBTC: { url: 'https://public-node.rsk.co', name: 'Rootstock', enabled: true, allowedEmptyValue: false },
  RBTC_TEST: { url: 'https://public-node.testnet.rsk.co', name: 'Rootstock Testnet', enabled: true, allowedEmptyValue: false },
  SGB: { url: 'https://sgb.ftso.com.au/ext/bc/C/rpc', name: 'Songbird', enabled: true, allowedEmptyValue: false },
  SGB_LEGACY: { url: undefined, name: 'Songbird Testnet', enabled: false, allowedEmptyValue: false },
  MOVR: { url: 'https://rpc.api.moonriver.moonbeam.network', name: 'MoonRiver', enabled: true, allowedEmptyValue: false },
  VLX_VLX: { url: 'https://api.velas.com', name: 'Velas', enabled: true, allowedEmptyValue: false },
  VLX_TEST: { url: 'https://api.testnet.velas.com', name: 'Velas Testnet', enabled: true, allowedEmptyValue: false },
  TKX: { url: undefined, name: 'TokenKX', enabled: true, allowedEmptyValue: true },
  ADA: { url: undefined, name: 'Cardano', enabled: true, allowedEmptyValue: true },
  ADA_TEST: { url: undefined, name: 'Cardano PreNet (Testnet)', enabled: true, allowedEmptyValue: true },
  MATIC_POLYGON: { url: 'https://polygon-bor-rpc.publicnode.com', name: 'Polygon', enabled: true, allowedEmptyValue: false },
  MATIC_POLYGON_MUMBAI: {
    url: 'https://polygon-mumbai-bor-rpc.publicnode.com',
    name: 'Polygon Mumbai Testnet',
    enabled: true,
    allowedEmptyValue: false,
  },
  AMOY_POLYGON_TEST: {
    url: 'https://polygon-amoy-bor-rpc.publicnode.com',
    name: 'Polygon Amoy Testnet',
    enabled: true,
    allowedEmptyValue: false,
  },
  'ETH-OPT': { url: 'https://mainnet.optimism.io', name: 'Optimism', enabled: true, allowedEmptyValue: false },
  'ETH-OPT_KOV': { url: 'https://kovan.optimism.io', name: 'Optimism Kovan Testnet', enabled: true, allowedEmptyValue: false },
  'ETH-AETH': { url: 'https://arbitrum.llamarpc.com', name: 'Arbitrum', enabled: true, allowedEmptyValue: false },
  'ETH-AETH_RIN': {
    url: 'https://rinkeby.arbitrum.io/rpc',
    name: 'Arbitrum Rinkbey Testnet',
    enabled: true,
    allowedEmptyValue: false,
  },
  BNB_BSC: { url: 'https://bsc-dataseed.binance.org', name: 'Binance', enabled: true, allowedEmptyValue: false },
  BNB_TEST: {
    url: 'https://data-seed-prebsc-1-s1.binance.org:8545/',
    name: 'Binance Testnet',
    enabled: true,
    allowedEmptyValue: false,
  },
  CORE_COREDAO: { url: 'https://rpc.coredao.org', name: 'Core DAO', enabled: true, allowedEmptyValue: false },
  CORE_COREDAO_TEST: { url: 'https://rpc.test.btcs.network', name: 'Core DAO Testent', enabled: true, allowedEmptyValue: false },
  EOS: { url: 'https://api.eoseoul.io', name: 'EOS', enabled: true, allowedEmptyValue: false },
  EOS_TEST: { url: 'https://jungle.eosusa.io', name: 'EOS Jungle Testnet', enabled: true, allowedEmptyValue: false },
  ATOM_COS: { url: 'https://cosmos-rpc.publicnode.com', name: 'Cosmos', enabled: true, allowedEmptyValue: false },
  ATOM_COS_TEST: {
    url: 'https://rpc.sentry-01.theta-testnet.polypore.xyz',
    name: 'Cosmos Theta Testnet',
    enabled: true,
    allowedEmptyValue: false,
  },
  TRX: { url: 'https://api.trongrid.io', name: 'Tron', enabled: true, allowedEmptyValue: false },
  TRX_TEST: { url: 'https://api.shasta.trongrid.io', name: 'Tron Shasta Testnet', enabled: true, allowedEmptyValue: false },
  LUNA2: { url: 'https://phoenix-lcd.terra.dev', name: 'Luna', enabled: true, allowedEmptyValue: false },
  LUNA2_TEST: { url: 'https://pisco-lcd.terra.dev/', name: 'Luna Testnet', enabled: true, allowedEmptyValue: false },
  XLM: { url: 'https://horizon.stellar.org/', name: 'Stellar', enabled: true, allowedEmptyValue: false },
  XLM_TEST: { url: 'https://horizon-testnet.stellar.org/', name: 'Stellar Testnet', enabled: true, allowedEmptyValue: false },
  NEAR: { url: 'https://rpc.mainnet.near.org', name: 'NEAR', enabled: true, allowedEmptyValue: false },
  NEAR_TEST: { url: 'https://rpc.testnet.near.org', name: 'NEAR Testnet', enabled: true, allowedEmptyValue: false },
  XTZ: { url: 'https://rpc.tzbeta.net', name: 'Tezos', enabled: true, allowedEmptyValue: false },
  XTZ_TEST: { url: 'https://ghostnet.smartpy.io', name: 'Tezos Ghostnet Testnet', enabled: true, allowedEmptyValue: false },
  XEM: { url: 'http://hugealice3.nem.ninja', name: 'NEM', enabled: true, allowedEmptyValue: false },
  XEM_TEST: { url: 'http://hugetestalice.nem.ninja', name: 'NEM Testnet', enabled: true, allowedEmptyValue: false },
  HBAR: { url: undefined, name: 'Hedera Hashgraph Testnet', enabled: true, allowedEmptyValue: true },
  HBAR_TEST: { url: undefined, name: 'Hedera Hashgraph', enabled: true, allowedEmptyValue: true },
  CELESTIA: { url: 'https://celestia-rpc.publicnode.com', name: 'Celestia', enabled: true, allowedEmptyValue: false },
  CELESTIA_TEST: {
    url: 'https://celestia-mocha-rpc.publicnode.com',
    name: 'Celestia Mocha Testnet',
    enabled: true,
    allowedEmptyValue: false,
  },
  TON_TEST: {
    url: 'https://testnet.toncenter.com/api/v2/jsonRPC',
    name: 'The Open Network - Testnet',
    enabled: true,
    allowedEmptyValue: false,
  },
  TON: {
    url: 'https://toncenter.com/api/v2/jsonRPC',
    name: 'The Open Network',
    enabled: true,
    allowedEmptyValue: false,
  },
  Jetton: {
    url: 'https://toncenter.com/api/v2/jsonRPC',
    name: 'The Open Network',
    enabled: true,
    allowedEmptyValue: false,
  },
};
